### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vaheminasyan** [wehkamp/docker-prometheus-cloudflare-exporter#11]
Hi all.
I cloned the repo and did some changes in order to add functionality to also export analytics by country( https://api.cloudflare.com/#zone-analytics-dashboard ).
Should I create a pull request or fork the repo and do changes there?
Sorry I really didn't find another way to ask this question.

**Comment by harmw** [comment]
I'm curious as to what that'll look like, looking forward to your PR 👍

**Comment by vaheminasyan** [comment]
Thanks. I'll review my code tomorrow and create the pull request.

**Comment by vaheminasyan** [comment]
Sorry for such a long pause. I was at vacation. I've created the PR.

**Comment by vaheminasyan** [comment]
Hi guys. Have you noticed my pull request? 🙂

**Comment by harmw** [comment]
noticed: yes
reviewed: terribly sorry, but not yet :(

Forgive me for taking long on this one!
