### ISSUE TITLE
Under what LICENSE is this code available.

### ISSUE THREAD

**Issue by totally** [wehkamp/docker-prometheus-cloudflare-exporter#12]
Folks may be blocked from using this code due to its lack of a LICENSE.  

Do you have a preference for licensing?  I'd be happy to send a PR adding this information.  If you don't have a preference, I could add BSD2.

Thank you!

**Comment by harmw** [comment]
We just merged PR13, adding LGPLv3 👍

**Comment by totally** [comment]
This is a big help, thank you very much!
