### ISSUE TITLE
Unable to pull from private registry

### ISSUE THREAD

**Issue by MrOffline77** [wehkamp/docker-prometheus-cloudflare-exporter#20]
Hello,
since merge #13 it is no longer possible to pull the docker container. Is this intentional ? 

There is a fork that provides the image public: 
https://hub.docker.com/r/osig/prometheus-cloudflare-exporter/tags

**Comment by johnkeates** [comment]
Hi @MrOffline77 It took us a while to notice but it has been fixed 👍
