### ISSUE TITLE
Metrics endpoint only returns comments

### ISSUE THREAD

**Issue by JorritSalverda** [wehkamp/docker-prometheus-cloudflare-exporter#3]
Hi, I'm testing your exporter - image wehkamp/prometheus-cloudflare-exporter:1.0 - in kubernetes, but so far no metrics.

The metrics endpoints returns this:

```
# HELP cloudflare_pop_threat_countries Threat breakdown per country.
# TYPE cloudflare_pop_threat_countries gauge
# HELP cloudflare_pop_received_requests Requests received at this PoP location.
# TYPE cloudflare_pop_received_requests gauge
# HELP cloudflare_pop_threats_seen Threats identified.
# TYPE cloudflare_pop_threats_seen gauge
# HELP cloudflare_pop_http_responses_sent Breakdown per HTTP response code.
# TYPE cloudflare_pop_http_responses_sent gauge
# HELP cloudflare_pop_threat_types Threat breakdown per threat type.
# TYPE cloudflare_pop_threat_types gauge
# HELP cloudflare_pop_bandwidth_bytes Bandwidth used from this PoP location.
# TYPE cloudflare_pop_bandwidth_bytes gauge
```

And the container log shows nothing except for:

```
2016-11-09T19:59:48.583869791Z Fetching data
```

Cpu and memory usage stays pretty much the same as well, so nothing really seems to happen. Any idea what could be wrong?

**Comment by harmw** [comment]
Looks like you're affected by https://www.cloudflarestatus.com/incidents/6k7j0294d8h9

Just be patient 😃

**Comment by harmw** [comment]
@JorritSalverda our graphs started showing data since a couple hours ago, can you confirm everything now works as expected?

**Comment by JorritSalverda** [comment]
Yes, the results are coming in now. Thanks for the awesome exporter!
